---
title: XX XX Manila
author: Club Braindance Corp.
email: info@20-20.asia
description: Bringing more quality electronic music to Manila
baseurl: "/ubuild-jekyll-xxxx"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
